# Mostly generated by Copilot 2026-06-10. Prompted by Adam Fong.

import os

def copy_file(src, dst):
    """Copy file using only built-in I/O."""
    with open(src, "rb") as fsrc, open(dst, "wb") as fdst:
        while True:
            chunk = fsrc.read(1024 * 1024)  # 1MB chunks
            if not chunk:
                break
            fdst.write(chunk)


def get_sorted_images(folder):
    valid_ext = ('.png', '.jpg', '.jpeg', '.bmp', '.tiff')
    return sorted(
        f for f in os.listdir(folder)
        if f.lower().endswith(valid_ext)
    )


def is_done(dst_folder, expected_count):
    """Check if sequence already copied."""
    if not os.path.exists(dst_folder):
        return False

    file_count = sum(
        1 for f in os.listdir(dst_folder)
        if os.path.isfile(os.path.join(dst_folder, f))
    )

    return file_count >= expected_count


def extract_sequences(
    src_root,
    dst_root,
    sequence_length=20,
    start_filename=None,
    label="high"
):
    os.makedirs(dst_root, exist_ok=True)

    for root, dirs, files in os.walk(src_root):

        images = get_sorted_images(root)

        if len(images) < sequence_length:
            continue

        # Determine start index from filename
        if start_filename:
            if start_filename not in images:
                print(f"{start_filename} not found in {root}, skipping")
                continue
            start_index = images.index(start_filename)
        else:
            start_index = 0

        if start_index + sequence_length > len(images):
            print(f"Not enough frames after {start_filename} in {root}")
            continue

        sequence = images[start_index:start_index + sequence_length]

        folder_name = os.path.basename(root)

        start_name_no_ext = os.path.splitext(images[start_index])[0]

        dst_folder = os.path.join(
            dst_root,
            f"{folder_name}_{start_name_no_ext}_{label}"
        )

        if is_done(dst_folder, sequence_length):
            print(f"Skipping {os.path.basename(dst_folder)} (already done)")
            continue

        os.makedirs(dst_folder, exist_ok=True)

        for img in sequence:
            src_path = os.path.join(root, img)
            dst_path = os.path.join(dst_folder, img)

            if os.path.exists(dst_path):
                continue

            copy_file(src_path, dst_path)

        print(f"Completed {os.path.basename(dst_folder)}")


# -------------------------
# USAGE
# -------------------------

base_src = "E:\\WidthVariation_S2026\\Experiment"
dst_root = "E:\\WidthVariation_S2026_annotations"

# low: 0-10 particles in frame
# med: 11-20 particles in frame
# high: 21+ particles in frame

## HIGH 
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780694996_509007800.jpg", label="high")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695008_905011900.jpg", label="high")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695022_818519900.jpg", label="high")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695026_775120100.jpg", label="high")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695042_818975000.jpg", label="high")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695045_905770800.jpg", label="high")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695000_513370400.jpg", label="high")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695006_296107800.jpg", label="high")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695007_600551300.jpg", label="high")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695009_122248400.jpg", label="high")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695011_296550500.jpg", label="high")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 200, start_filename="1780695018_252978600.jpg", label="high")

## MEDIUM
extract_sequences(os.path.join(base_src, "01-02"), dst_root, 20, start_filename="1780936976_662246800.jpg", label="med")
extract_sequences(os.path.join(base_src, "01-02"), dst_root, 20, start_filename="1780936980_660862100.jpg", label="med")
extract_sequences(os.path.join(base_src, "01-02"), dst_root, 20, start_filename="1780936984_443527800.jpg", label="med")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695030_862058000.jpg", label="med")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695809_231158600.jpg", label="med")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695812_666327600.jpg", label="med")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695816_100796400.jpg", label="med")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695826_579630200.jpg", label="med")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780696023_280371900.jpg", label="med")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780696109_195879500.jpg", label="med")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780696107_413129500.jpg", label="med")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780698255_123791800.jpg", label="med")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780698407_432549700.jpg", label="med")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780698498_999595300.jpg", label="med")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695620_661071200.jpg", label="med")
extract_sequences(os.path.join(base_src, "02-03"), dst_root, 20, start_filename="1780949628_090569300.jpg", label="med")
extract_sequences(os.path.join(base_src, "02-03"), dst_root, 20, start_filename="1780956034_264691600.jpg", label="med")
extract_sequences(os.path.join(base_src, "02-03"), dst_root, 20, start_filename="1780958686_250063500.jpg", label="med")
extract_sequences(os.path.join(base_src, "04-05"), dst_root, 20, start_filename="1781022736_102633100.jpg", label="med")
extract_sequences(os.path.join(base_src, "04-05"), dst_root, 20, start_filename="1781023487_165526000.jpg", label="med")
extract_sequences(os.path.join(base_src, "04-05"), dst_root, 20, start_filename="1781023859_350035600.jpg", label="med")
extract_sequences(os.path.join(base_src, "04-05"), dst_root, 20, start_filename="1781024666_414867300.jpg", label="med")

## LOW
extract_sequences(os.path.join(base_src, "05-06"), dst_root, 20, start_filename="1781038208_410876700.jpg", label="low")
extract_sequences(os.path.join(base_src, "05-06"), dst_root, 20, start_filename="1781038445_851888300.jpg", label="low")
extract_sequences(os.path.join(base_src, "05-06"), dst_root, 20, start_filename="1781040931_919354500.jpg", label="low")
extract_sequences(os.path.join(base_src, "05-06"), dst_root, 20, start_filename="1781040946_223837100.jpg", label="low")
extract_sequences(os.path.join(base_src, "05-06"), dst_root, 20, start_filename="1781040948_964214100.jpg", label="low")
extract_sequences(os.path.join(base_src, "05-06"), dst_root, 20, start_filename="1781041524_978535100.jpg", label="low")
extract_sequences(os.path.join(base_src, "05-06"), dst_root, 20, start_filename="1781041537_587504400.jpg", label="low")
extract_sequences(os.path.join(base_src, "05-06"), dst_root, 20, start_filename="1781041795_378990900.jpg", label="low")
extract_sequences(os.path.join(base_src, "01-02"), dst_root, 20, start_filename="1780936257_941121300.jpg", label="low")
extract_sequences(os.path.join(base_src, "01-02"), dst_root, 20, start_filename="1780936921_659109500.jpg", label="low")
extract_sequences(os.path.join(base_src, "01-02"), dst_root, 20, start_filename="1780936955_182085700.jpg", label="low")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780695820_971024400.jpg", label="low")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780696688_341975400.jpg", label="low")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780697022_785778700.jpg", label="low")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780697242_227011000.jpg", label="low")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780697557_887317100.jpg", label="low")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780697614_845301100.jpg", label="low")
extract_sequences(os.path.join(base_src, "00-01"), dst_root, 20, start_filename="1780697724_718748100.jpg", label="low")
extract_sequences(os.path.join(base_src, "02-03"), dst_root, 20, start_filename="1780949798_877950900.jpg", label="low")
extract_sequences(os.path.join(base_src, "03-04"), dst_root, 20, start_filename="1780955299_462311000.jpg", label="low")
extract_sequences(os.path.join(base_src, "03-04"), dst_root, 20, start_filename="1780956148_398546400.jpg", label="low")
extract_sequences(os.path.join(base_src, "03-04"), dst_root, 20, start_filename="1780956664_977859100.jpg", label="low")